### ISSUE TITLE
Remove transpiler dependency.

### ISSUE THREAD

**Issue by vsviridov** [bidanjun/koa-graphql-next#10]
Modules are not natively supported, and bringing the transpiler just for one backend module is sometimes overkill...

**Comment by bidanjun** [comment]
Modules are not natively supported,what?

**Comment by vsviridov** [comment]
the `import from` syntax. on the server-side it's all `require`.
Async is in node 7.x, so the only need for a transpiler is for the `import` syntax, which is not really necessary and can be avoided server-side.

**Comment by bidanjun** [comment]
yes,it's only for this ways:)
and,of course,at front side,the newest react component, need babel and webpack too..
i think,we could use the same ways at server and client.
as you see,i just change test fromwork from ava to jest, for the same reason....you can't using the new stack with out babel.

async/await is the best ways instead promise and callback function, I can't back,sorry.... .

**Comment by bidanjun** [comment]
and ofcourse, if u use it from npm, you are use an version that covert to es5 already.
we publish a translated version to npm.
